config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with twitter and github
  get 'ouath/:provider' => 'oauths#oauth', :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login
  get 'signup' => 'registrations#new', :as => :signup

  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :registrations
  resources :profile
  resources :cards
  resources :packs

  root to: 'home#index'

end

app/models/pack.rb
class Pack < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  belongs_to :user

  validates :name, uniqueness: true, presence: true
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :find_pack, only: [:show, :edit, :update, :destroy]

  def index
    @packs = current_user.packs.all
  end

  def new
    @pack = current_user.packs.new
  end

  def create
    @pack = current_user.packs.new(pack_params)

    if @pack.save
      redirect_to @pack, notice: t('views.packs.flash_messages.pack_was_successfully_created')
    else
      render 'new'
    end
  end

  def update
    if @pack.update(pack_params)
      redirect_to @pack, notice: t('views.packs.flash_messages.pack_was_successfully_updated')
    else
      render 'edit'
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @pack.destroy

    redirect_to packs_path
  end

  private
    def pack_params
      params.require(:pack).permit(:name)
    end

    def find_pack
      @pack = current_user.packs.find(params[:id])
    end
end

app/views/packs/_form.html.erb
<%= simple_form_for pack do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, t('forms.buttons.submit') %>
<% end %>

app/views/packs/edit.html.erb
<h3><%= t('views.packs.edit.h3') %></h3>
<%= render "form", pack: @pack %>
<%= link_to t('views.back'), packs_path %>
<p id="notice"><%= notice %></p>

app/views/packs/index.html.erb
<h3><%= t('views.packs.index.h3') %></h3>
<p id="notice"><%= notice %></p>
<p>
  <%= link_to t('views.packs.index.set_default_pack'), edit_profile_path(current_user) %>
</p>
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= Pack.human_attribute_name(:name) %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <% @packs.each do |pack| %>
    <tbody>
    <tr>
      <td><%= pack.name %></td>
      <td><%= link_to t('views.edit'), edit_pack_path(pack) %></td>
      <td><%= link_to t('views.destroy'), pack_path(pack),
                      method: :delete,
                      data: { confirm: "#{t('views.are_you_sure')}" } %></td>
    </tr>
    </tbody>
  <% end %>
</table>

app/views/packs/new.html.erb
<h3><%= t('views.packs.new.h3') %></h3>
<%= render "form", pack: @pack %>
<%= link_to t('views.back'), packs_path %>
<p id="notice"><%= notice %></p>

app/views/packs/show.html.erb
<h3><%= t('views.packs.show.h3') %><%= @pack.id %></h3>
<p>
  <label><%= Pack.human_attribute_name(:name) %></label>
  <%= @pack.name %>
</p>
<%= link_to t('views.back'), packs_path %>