config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with twitter and github
  get 'ouath/:provider' => 'oauths#oauth', :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login
  get 'signup' => 'registrations#new', :as => :signup

  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :registrations
  resources :profile
  resources :cards
  resources :packs

  root to: 'home#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :pack

  scope :for_review, -> { where("review_date <= ?", DateTime.now).order("RANDOM()") }

  has_attached_file :image,
    styles: { thumb: "100x100>", large: "360x360#" },
    default_url: "/images/:style/missing.png"

  before_create :set_default_review_date

  validates :pack_id, presence: true
  validates :original_text, :translated_text, :review_date, presence: true

  validate :original_text_cannot_be_equal_translated_text

  validates_attachment :image,
    content_type: { content_type: ["image/jpeg", "image/png"] },
    size: { in: 0..5.megabytes }

  def self.create_from_pack(user, card_params)
    pack_name = card_params.delete(:new_pack_name)
    if pack_name.present?
      new_pack = user.packs.find_or_create_by(name: pack_name)
      card = new_pack.cards.new(card_params.merge(pack_id: new_pack.id))
    else
      pack = user.packs.find_by(id: card_params[:pack_id])
      card = pack.cards.new(card_params)
    end
    card
  end

  def update_from_pack(user, card_params)
    pack_name = card_params.delete(:new_pack_name)
    if pack_name.present?
      new_pack = user.packs.find_or_create_by(name: pack_name)
      update(card_params.merge(pack_id: new_pack.id))
    else
      update(card_params)
    end
  end

  def verify_translation(user_translation, translation_time)
    time = translation_time.to_i

    result = transform_string(original_text) == transform_string(user_translation)

    quantity_of_response = result ? SM2CardsReviewer.translating_card_time(time) : 0

    sm2 = SM2CardsReviewer.new(self.easiness_factor, self.number_repetitions,
                               self.repetition_interval, self.review_date)

    sm2.processing_count_result(quantity_of_response)

    update(easiness_factor: sm2.easiness_factor,
           number_repetitions: sm2.number_repetitions,
           repetition_interval: sm2.repetition_interval,
           review_date: sm2.review_date)
    result
  end

  private
    def original_text_cannot_be_equal_translated_text
      if original_text.mb_chars.downcase == translated_text.mb_chars.downcase
        errors.add(:translated_text, I18n.t('views.cards.flash_messages.original_text_not_equal_translated_text'))
      end
    end

    def set_default_review_date
      self.review_date = DateTime.now
    end

    def transform_string(str)
      str.squish.mb_chars.downcase # remove spaces and downcase string (mb_chars - for UTF-8 encoding)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = current_user.cards.all
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.create_from_pack(current_user, card_params)
    if @card.save
      redirect_to @card, notice: t('views.cards.flash_messages.card_was_successfully_created')
    else
      render 'new'
    end
  end

  def update
    if @card.update_from_pack(current_user, card_params)
      redirect_to @card, notice: t('views.cards.flash_messages.card_was_successfully_updated')
    else
      render 'edit'
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @card.destroy

    redirect_to cards_path
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date,
                                   :image, :pack_id, :new_pack_name)
    end

    def find_card
      @card = Card.find(params[:id])
    end
end

app/views/cards/_form.html.erb
<%= simple_form_for card do |f| %>
  <%= f.input :original_text %>
  <%= f.input :translated_text %>
  <%= f.input :image, as: :file %>
  <%= f.input :review_date, as: :date %>
  <%= label_tag t('views.cards.new.label_tag_new_pack') %>
  <%= text_field_tag 'card[new_pack_name]' %>
  <%= f.input :pack_id, collection: current_user.packs.all, selected: card.pack_id %>
  <%= f.button :submit, t('forms.buttons.submit') %>
<% end %>

app/views/cards/edit.html.erb
<h3><%= t('views.cards.edit.h3') %></h3>
<%= render "form", card: @card %>
<%= link_to t('views.back'), cards_path %>
<p id="notice"><%= notice %></p>

app/views/cards/index.html.erb
<h3><%= t('views.cards.index.h3') %></h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= Pack.human_attribute_name(:name) %></th>
      <th><%= Card.human_attribute_name(:original_text) %></th>
      <th><%= Card.human_attribute_name(:translated_text) %></th>
      <th><%= Card.human_attribute_name(:image) %></th>
      <th><%= Card.human_attribute_name(:review_date) %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <% @cards.each do |card| %>
    <tbody>
      <tr>
        <td><%= card.pack.name %></td>
        <td><%= card.original_text %></td>
        <td><%= card.translated_text %></td>
        <td><%= card.image_file_name %></td>
        <td><%= l card.review_date, format: :short %></td>
        <td><%= link_to t('views.edit'), edit_card_path(card) %></td>
        <td><%= link_to t('views.destroy'), card_path(card),
                        method: :delete,
                        data: { confirm: "#{t('views.are_you_sure')}" } %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/cards/new.html.erb
<h3><%= t('views.cards.new.h3') %></h3>
<%= render "form", card: @card %>
<%= link_to t('views.back'), cards_path %>
<p id="notice"><%= notice %></p>

app/views/cards/show.html.erb
<h3><%= t('views.cards.show.h3') %><%= @card.id %></h3>
<p>
  <label><%= Card.human_attribute_name(:original_text) %></label>
  <%= @card.original_text %>
</p>
<p>
  <label><%= Card.human_attribute_name(:translated_text) %></label>
  <%= @card.translated_text %>
</p>
<p>
  <label><%= Card.human_attribute_name(:image) %></label>
  <%= image_tag @card.image(:large) %>
</p>
<p>
  <label><%= Card.human_attribute_name(:review_date) %></label>
  <%= @card.review_date.strftime("%d/%m/%Y") %>
</p>
<p>
  <label><%= Pack.human_attribute_name(:name) %></label>
  <%= @card.pack.name %>
</p>
<%= link_to t('views.back'), cards_path %>