config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with twitter and github
  get 'ouath/:provider' => 'oauths#oauth', :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login
  get 'signup' => 'registrations#new', :as => :signup

  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :registrations
  resources :profile
  resources :cards
  resources :packs

  root to: 'home#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @card = current_user.review_cards.first
  end

  def create
    @card = current_user.cards.find(review_params[:card_id])

    respond_to do |format|
      if @result = @card.verify_translation(review_params[:user_translation], review_params[:translation_time])
        format.html {
          redirect_to :back,
          notice: t('views.reviews.flash_messages.user_translated_correct')
        }
        format.json { render json: @result }
      else
        format.html {
          redirect_to :back,
          notice: t('views.reviews.flash_messages.user_translated_incorrect')
        }
        format.json { render json: @result }
      end
    end
  end

  private
    def review_params
      params.require(:review).permit(:card_id, :translation_time, :user_translation)
    end
end

app/views/reviews/new.html.erb
<% if @card.nil? %>
  <p class="text-danger lead"><%= t('views.reviews.nil_cards_label') %></p>
<% else %>
  <h3><%= t('views.cards.show.h3') %><%= @card.id %></h3>
  <p class="text-info"><%= Card.human_attribute_name(:translated_text) %>:</p>
  <%= @card.translated_text %>
  <%= simple_form_for :review, url: reviews_path,
                      method: :post, html: { id: "form-translation" } do |f| %>
    <%= f.input :user_translation %>
    <%= f.hidden_field :translation_time %>
    <%= f.hidden_field :card_id, value: @card.id %>
    <%= f.button :submit, t('simple_form.buttons.review.submit') %>
  <% end %>
  <br />
  <p class="text-danger lead"><%= notice %></p>
  <%= image_tag @card.image.url(:large) %>
<% end %>