config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with twitter and github
  get 'ouath/:provider' => 'oauths#oauth', :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login
  get 'signup' => 'registrations#new', :as => :signup

  resources :sessions, only: [:new, :create, :destroy]
  resources :reviews
  resources :registrations
  resources :profile
  resources :cards
  resources :packs

  root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('page_title') %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default">
  <div class="container">
    <div style="text-align: right;">
      <%= link_to_unless I18n.locale == :ru, "RU", locale: :ru %> |
      <%= link_to_unless I18n.locale == :en, "EN", locale: :en %>
    </div>
    <h2 class="text-muted"><%= t('views.h2_title_class_muted') %></h2>
    <div class="user nav">
      <% if current_user %>
        <%= t('views.current_user_label') %>: <%= current_user.email %> |
        <%= link_to t('menu.edit_profile'), edit_profile_path(current_user.id) %> |
        <%= link_to t('menu.logout'), logout_path %>
      <% else %>
        <%= link_to t('menu.registration'), signup_path %> |
        <%= link_to t('menu.login'), login_path %>
      <% end %>
    </div>
    <div style="text-align: left;">
      <%= link_to t('menu.sign_in_github'), auth_at_provider_path(provider: :github) %> |
      <%= link_to t('menu.sign_in_twitter'), auth_at_provider_path(provider: :twitter) %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('menu.all_packs'), packs_path %></li>
        <li><%= link_to t('menu.all_cards'), cards_path %></li>
        <li><%= link_to t('menu.new_pack'), new_pack_path %></li>
        <li><%= link_to t('menu.new_card'), new_card_path %></li>
      </ul>
    </nav>
    <p id="alert"><%= alert %></p>
    <p id="notice"><%= notice %></p>
  </div>
</header>

<div class="container">
  <%= yield %>
</div>

</body>
</html>